apiVersion: v1
kind: Pod
metadata:
  name: example-pod
  namespace: default
  labels:
    app: sample-web-app
spec:
  containers:
  - image: yks0000/echoserver:latest
    imagePullPolicy: Always
    name: rest-api
    ports:
    - containerPort: 8080
      protocol: TCP
  - image: nginx:stable
    imagePullPolicy: Always
    name: nginx-webserver
    ports:
      - containerPort: 443
        protocol: TCP
    volumeMounts:
      - mountPath: "/etc/nginx/nginx.conf"
        subPath: "nginx.conf"
        name: "nginx-conf"
      - mountPath: "/etc/nginx/ssl"
        name: "nginx-tls"
        readOnly: true
  volumes:
    - name: nginx-conf
      configMap:
        name: nginx-conf
    - name: nginx-tls
      secret:
        secretName: sidecar-injector-certs