apiVersion: v1
kind: Pod
metadata:
  name: example-pod
  labels:
    inject-nginx-sidecar: "true"
spec:
  containers:
    - name: rest-api
      image: yks0000/echoserver:latest
      imagePullPolicy: Always
      ports:
        - containerPort: 8080
          protocol: TCP